version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:postgres@database/app"
    volumes:
      - .:/app

  database:
    image: postgres:12
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/tmp/
