version: "3.8"

services:
  app:
    build: .
    environment:
      PROJECT_NAME: "axione"
      BACKEND_CORS_ORIGINS: ("http://localhost:8000", "https://localhost:8000", "http://localhost", "https://localhost")
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SERVER: database
      POSTGRES_DB: app
      DATABASE_URL: "postgresql+psycopg2://postgres:postgres@database/app"
    ports:
      - "8000:8000"

    volumes:
      - .:/app

  database:
    image: postgres:12

    ports:
      - "5432:5432"
    environment:
      PROJECT_NAME: "axione"
      BACKEND_CORS_ORIGINS: ("http://localhost:8000", "https://localhost:8000", "http://localhost", "https://localhost")
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_SERVER: database
      POSTGRES_DB: app
    volumes:
      - ./postgres:/var/tmp/
