"""generate_db_models

Revision ID: 2d96255bd280
Revises:
Create Date: 2023-02-27 08:39:04.456103

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "2d96255bd280"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "department",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "city_information",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("insee_code", sa.String(length=10), nullable=False),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("population", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("insee_code"),
    )
    op.create_index(
        op.f("ix_city_information_department_id"),
        "city_information",
        ["department_id"],
        unique=False,
    )
    op.create_table(
        "apartment_rent_indicator",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("square_meter_rent", sa.Float(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["city_information.id"],
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["department.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_apartment_rent_indicator_city_id"),
        "apartment_rent_indicator",
        ["city_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_apartment_rent_indicator_department_id"),
        "apartment_rent_indicator",
        ["department_id"],
        unique=False,
    )
    op.create_table(
        "city_zipcode",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zipcode", sa.String(length=15), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["city_id"],
            ["city_information.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_city_zipcode_city_id"), "city_zipcode", ["city_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_city_zipcode_city_id"), table_name="city_zipcode")
    op.drop_table("city_zipcode")
    op.drop_index(
        op.f("ix_apartment_rent_indicator_department_id"),
        table_name="apartment_rent_indicator",
    )
    op.drop_index(
        op.f("ix_apartment_rent_indicator_city_id"),
        table_name="apartment_rent_indicator",
    )
    op.drop_table("apartment_rent_indicator")
    op.drop_index(
        op.f("ix_city_information_department_id"), table_name="city_information"
    )
    op.drop_table("city_information")
    op.drop_table("department")
    # ### end Alembic commands ###
