name: Python test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and test
        run: |
          docker-compose up --build -d
      - name: Populate data
        run: |
           docker-compose exec -i database bash /var/tmp/setup.sh
      - name: Running tests
        run: |
            docker-compose exec -i app pytest
